name: rich_text_view
description: A simple yet powerful rich text view that supports mention, hashtag, email, url and see more.
version: 1.9.0
homepage: https://github.com/nelsonweze/rich_text_view

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

flutter:

